name: DEV Start Program

on:
  push:
    branches:
      - chore/use-ubiquity-os-auth

jobs:
  run-start:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com" > ~/.git-credentials

      - name: Run start script
        run: bun run start "https://github.com/ubiquity/.ubiquity-os.git"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: "insert all missing defaults"
          INTERACTIVE: "false"
          ACTOR: "ubiquity-os[bot]"
          EMAIL: "ubiquity-os[bot]@users.noreply.github.com"
          AUTH_TOKEN: ${{ steps.generate_token.outputs.token }}
