name: DEV Start Program

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  run-start:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Get Installation ID
        id: get_installation
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.apps.getOrgInstallation({
              org: 'ubiquity'
            });
            core.setOutput('installation_id', data.id.toString());

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: "${{ steps.get_installation.outputs.installation_id }}"

      - name: Configure Git
        run: |
          git config --global user.name "ubiquity-os[bot]"
          git config --global user.email "ubiquity-os[bot]@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://ubiquity-os[bot]:${{ steps.generate_token.outputs.token }}@github.com" > ~/.git-credentials

      - name: Run start script
        run: bun run start "https://github.com/ubiquity/.ubiquity-os.git"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: "insert all missing defaults"
          INTERACTIVE: "false"
          ACTOR: "ubiquity-os[bot]"
          EMAIL: "ubiquity-os[bot]@users.noreply.github.com"
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          USE_MOCK_CLAUDE_RESPONSE: "true"
          AUTH_TOKEN: ${{ steps.generate_token.outputs.token }}
          APP_INSTALLATION_ID: "${{ steps.get_installation.outputs.installation_id }}"
