name: DEV Start Program

on:
  push:
    branches:
      - fix/actions-auth-3

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  run-start:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://${{ github.actor }}:${{ github.token }}@github.com" > ~/.git-credentials

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run start script
        run: bun run start "https://github.com/ubiquity/.ubiquity-os.git"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: "insert all missing defaults"
          INTERACTIVE: "false"
          GITHUB_ACTOR: ${{ github.actor }}
          # GITHUB_TOKEN: ${{ github.token }}
          # GIT_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GIT_AUTH_TOKEN: ${{ github.token }}
