name: Start Program

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: "Input string to pass to the program"
        required: true
        type: string

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run start script
        run: npm start "${{ github.event.inputs.input_string }}"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_STRING: ${{ github.event.inputs.input_string }}
          INTERACTIVE: "false"