name: Start Program

on:
  workflow_dispatch:
    inputs:
      editor_instruction:
        description: "Provide instructions for editing the YAML configuration. More detailed and specific instructions will yield better results."
        required: true
        type: string
      target_repo:
        description: "URL of the git repository to target (optional)"
        required: false
        type: string

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run start script
        run: npm start ${{ github.event.inputs.target_repo }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: ${{ github.event.inputs.editor_instruction }}
          INTERACTIVE: "false"
