name: Start Program

on:
  workflow_dispatch:
    inputs:
      editor_instruction:
        description: "Provide instructions for editing the YAML configuration. More detailed and specific instructions will yield better results."
        required: true
        type: string
      target_repo:
        description: "URL of the git repository to target (optional)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Configure Git credentials
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ github.token }}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run start script
        run: bun run start ${{ github.event.inputs.target_repo }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: ${{ github.event.inputs.editor_instruction }}
          INTERACTIVE: "false"
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
