name: Start Program

on:
  workflow_dispatch:
    inputs:
      editor_instruction:
        description: "Provide instructions for editing the YAML configuration. More detailed and specific instructions will yield better results."
        required: true
        type: string
      target_repo:
        description: "URL of the git repository to target (optional)"
        required: false
        type: string

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run start script
        run: bun run start ${{ github.event.inputs.target_repo }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EDITOR_INSTRUCTION: ${{ github.event.inputs.editor_instruction }}
          INTERACTIVE: "false"
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_APP_TOKEN: ${{ steps.generate_token.outputs.token }}